trigger:
  - master

variables:
  powershell: 'true'

pool:
  vmName: 'windows-latest'

jobs:
  - job:
    dependsOn: '1job'
    steps:
      - powershell: 'Write-Output'

# stages:
#   - stage: etap
#     displayName: 'build'
#     pool:
#       vmName: 'ubuntu-latest'
#     jobs:
#       - job:
#         displayName: 'zadanie 1'
#         steps:
#           - powershell: |
#               Write-Output 'zadanie 1'
#           - pwsh: Write-Output 'zadanie 2'
