trigger:
  - master

variables:
  powershell: 'true'

stages:
  - stage: etap
    displayName: 'build'
    pool:
      vmName: 'ubuntu-latest'
    jobs:
      - job:
        dependsOn: 'zadanie 1'
        steps:
          - powershell: |
              Write-Output 'zadanie 1'
          - pwsh: Write-Output 'zadanie 2'
